### ISSUE TITLE
Making alerts on new case reported

### ISSUE THREAD

**Issue by Kishiko** [devscast/covid19-notifier#2]
At that moment, the application pushes SMS notification sometimes when there is news related to the disease in DRC. But not each case (a new case, a recovery one and a fatal one) reported is pushed.

While every day DRC records at least one case, it would be better to send that notification to all subscribers.

**Comment by bernard-ng** [comment]
as for your first issue #1  on the project, beyond the code, the finances are necessary for what you ask there, the messages sent are the most important at our level, for new cases we make a global situation every two-three days and we send it as a summary of the situation

**Comment by bernard-ng** [comment]
@Kishiko  our application is not financially supported by the government so far, and to broadcast messages to more than 20k users is a huge cost for us this is why we judge which messages are the most important to reduce our spending
